### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'tensor_type

### ISSUE THREAD

**Issue by mohsinjuni** [sebastianGehrmann/bottom-up-summary#5]
First of all, thanks for uploading pretrained model and prediction outputs. It's really helpful. 

To produce prediction output using pretrained model, I am using following command but I am getting given below error. There seems to be model-loading issue. Could you please help on this? Also, did I provide the correct parameters?

Thanks.

Command:
```
python translate.py -model ./bottomUpModel/ada6_bridge_oldcopy_tagged_larger_acc_54.84_ppl_10.58_e17.pt \
                    -src ./bottomUpModel/test.txt.src \
                    -constraint_file ./bottomUpModel/allennlp_test_output.txt \
                    -threshold 0.15 \
                    -batch_size 1 \
                    -min_length 35 \
                    -stepwise_penalty \
                    -coverage_penalty summary \
                    -beta 5 \
                    -length_penalty wu \
                    -alpha 0.9 \
                    -block_ngram_repeat 3 \
                    -ignore_when_blocking "." "" "" \
                    -output ./bottomUpModel/prediction \
                    -gpu 0

```
Error:

```
Traceback (most recent call last):
  File "translate.py", line 162, in <module>
    main()
  File "translate.py", line 67, in main
    onmt.ModelConstructor.load_test_model(opt, dummy_opt.__dict__)
  File "./bottomUpModel/OpenNMT-py-copy_constraint/onmt/ModelConstructor.py", line 121, in load_test_model
    checkpoint['vocab'], data_type=opt.data_type)
  File "./bottomUpModel/OpenNMT-py-copy_constraint/onmt/io/IO.py", line 57, in load_fields_from_vocab
    fields = get_fields(data_type, n_src_features, n_tgt_features)
  File "./bottomUpModel/OpenNMT-py-copy_constraint/onmt/io/IO.py", line 43, in get_fields
    return TextDataset.get_fields(n_src_features, n_tgt_features)
  File "./bottomUpModel/OpenNMT-py-copy_constraint/onmt/io/TextDataset.py", line 231, in get_fields
    postprocessing=make_src, sequential=False)
TypeError: __init__() got an unexpected keyword argument 'tensor_type'
```

**Comment by mohsinjuni** [comment]
Turns out that there was an additional argument of 'tensor_type' in TextDataset.py for 3 different function calls. After removing that, those error disappeared. Now, I am getting other warnings + dimension-related errors. May be, pytorch version issues (mine is: 0.4.1.post2)?

```
average src size 778.2678851174935 11490
The `device` argument should be set by using `torch.device` or passing a string as an argument. This behavior will be deprecated soon and currently defaults to cpu.
/home/mohsin.j/language_translation/bottomUpModel/OpenNMT-py-copy_constraint/onmt/translate/Translator.py:99: **UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  def var(a): return Variable(a, volatile=True)**
/home/mohsin.j/language_translation/bottomUpModel/OpenNMT-py-copy_constraint/onmt/Models.py:667: **UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  for e in self._all]**
/home/mohsin.j/language_translation/bottomUpModel/OpenNMT-py-copy_constraint/onmt/modules/GlobalAttention.py:176: **UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.**
  align_vectors = self.sm(align.view(batch*targetL, sourceL))
/home/mohsin.j/language_translation/bottomUpModel/OpenNMT-py-copy_constraint/onmt/modules/CopyGenerator.py:92: **UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  prob = F.softmax(logits)**
/home/mohsin.j/miniconda3/lib/python3.6/site-packages/torch/nn/functional.py:1006: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")
Traceback (most recent call last):
  File "translate.py", line 162, in <module>
    main()
  File "translate.py", line 126, in main
    batch_data = translator.translate_batch(batch, data, tags)
  File "/home/mohsin.j/language_translation/bottomUpModel/OpenNMT-py-copy_constraint/onmt/translate/Translator.py", line 168, in translate_batch
    tags=tags)
  File "/home/mohsin.j/language_translation/bottomUpModel/OpenNMT-py-copy_constraint/onmt/modules/CopyGenerator.py", line 105, in forward
    tags = tags.expand_as(attn)
**RuntimeError: The expanded size of the tensor (1311) must match the existing size (400) at non-singleton dimension 1**

```

Thanks for your help in advance.

**Comment by leoribeiro** [comment]
@mohsinjuni I'm having the same problem. Were you able to run the model?

**Comment by mohsinjuni** [comment]
No, I didn't get time to explore further. I am still waiting to get some pointers from the author himself. If you get to find a way out, please do share.

**Comment by 457138317** [comment]
you may can  install the https://github.com/pytorch/text to fix this problem

**Comment by sebastianGehrmann** [comment]
Please use the pytorch version named as requirement in the `copy_constraint` requirements.txt. Then it should work
