### ISSUE TITLE
Is the emlo_tagger.json complete?

### ISSUE THREAD

**Issue by Runingtime** [sebastianGehrmann/bottom-up-summary#6]
Hi,
I got the following error when using the emlo_tagger configuration.

> Traceback (most recent call last):
  File "/home/server3/.conda/envs/pyth_3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/server3/.conda/envs/pyth_3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/server3/.conda/envs/pyth_3/lib/python3.6/site-packages/allennlp/run.py", line 18, in <module>
    main(prog="allennlp")
  File "/home/server3/.conda/envs/pyth_3/lib/python3.6/site-packages/allennlp/commands/__init__.py", line 72, in main
    args.func(args)
  File "/home/server3/.conda/envs/pyth_3/lib/python3.6/site-packages/allennlp/commands/train.py", line 111, in train_model_from_args
    args.force)
  File "/home/server3/.conda/envs/pyth_3/lib/python3.6/site-packages/allennlp/commands/train.py", line 142, in train_model_from_file
    return train_model(params, serialization_dir, file_friendly_logging, recover, force)
  File "/home/server3/.conda/envs/pyth_3/lib/python3.6/site-packages/allennlp/commands/train.py", line 298, in train_model
    model = Model.from_params(vocab=vocab, params=params.pop('model'))
  File "/home/server3/.conda/envs/pyth_3/lib/python3.6/site-packages/allennlp/common/from_params.py", line 274, in from_params
    return subclass.from_params(params=params, **extras)
  File "/home/server3/.conda/envs/pyth_3/lib/python3.6/site-packages/allennlp/common/from_params.py", line 285, in from_params
    kwargs = create_kwargs(cls, params, **extras)
  File "/home/server3/.conda/envs/pyth_3/lib/python3.6/site-packages/allennlp/common/from_params.py", line 150, in create_kwargs
    raise ConfigurationError(f"expected key {name} for {cls.__name__}")
allennlp.common.checks.ConfigurationError: 'expected key encoder for SimpleTagger'
[INFO/MainProcess] process shutting down

How can I fix it?

**Comment by sebastianGehrmann** [comment]
What allennlp version did you try? you might have a version that is too new.

**Comment by Runingtime** [comment]
Thanks

**Comment by duytue** [comment]
I got the same error. Can i ask what version of allennlp should i install?

**Comment by bckim92** [comment]
@duytue 
After the very initial version of allennlp, they changed naming convention for elmo encoder from `stacked_encoder` to `encoder` (related commit: https://github.com/allenai/allennlp/commit/acf21a53e7001bb6c7c3f7113c0d2805ffccceb2).
So, I solved this problem by changing all the `stacked_encoder` in json files to `encoder`.
I tested it with `allennlp==0.8.1` and it works fine
